#!/bin/bash

deactivate 2>/dev/null || true

# Set TS_REPO_ROOT variable, important for compilation flow
echo "Setting TS_REPO_ROOT to: `pwd`"
export TS_REPO_ROOT=`pwd`

# Set TS_DESIGN_NAME variable, important for synthesis flow
echo "Setting TS_DESIGN_NAME to: spect_top"
export TS_DESIGN_NAME="spect_top"

# Set language of TS_COMMON_BLOCKS which is used
export TS_COMMON_BLOCKS_LANG=sv

# Generate temporary file which will configure SW
ts_sw_cfg.py -v ts_sw_setup.yml

# Source it and get rid of it
source ./source_me_to_get_all_set
rm source_me_to_get_all_set

